# models/staging/_sources.yml

version: 2

sources:
  - name: snowflake_public_data
    database: SNOWFLAKE_PUBLIC_DATA_PAID
    schema: PUBLIC_DATA
    tables:
      # GLUE
      - name: GEOGRAPHY_INDEX
      - name: GEOGRAPHY_HIERARCHY
      - name: GEOGRAPHY_RELATIONSHIPS
      - name: GEOGRAPHY_CHARACTERISTICS

      # LAYER 1: DISASTER
      - name: FEMA_DISASTER_DECLARATION_INDEX
      - name: FEMA_DISASTER_DECLARATION_AREAS_INDEX
      - name: FEMA_MISSION_ASSIGNMENT_INDEX
      - name: FEMA_REGION_INDEX
      - name: FEMA_NATIONAL_FLOOD_INSURANCE_PROGRAM_CLAIM_INDEX
      - name: FEMA_NATIONAL_FLOOD_INSURANCE_PROGRAM_POLICY_INDEX
      - name: NOAA_WEATHER_METRICS_TIMESERIES
      - name: NOAA_WEATHER_METRICS_ATTRIBUTES
      - name: NOAA_WEATHER_STATION_INDEX
      - name: NWS_WEATHER_ALERT_EVENTS
      - name: NWS_WEATHER_ZONE_INDEX

      # LAYER 2: HOUSING IMPACT
      - name: FHFA_HOUSE_PRICE_TIMESERIES
      - name: FHFA_HOUSE_PRICE_ATTRIBUTES
      - name: US_REAL_ESTATE_TIMESERIES
      - name: US_REAL_ESTATE_ATTRIBUTES
      - name: FREDDIE_MAC_HOUSING_TIMESERIES
      - name: FREDDIE_MAC_HOUSING_ATTRIBUTES
      - name: FHFA_MORTGAGE_PERFORMANCE_TIMESERIES
      - name: HOUSING_URBAN_DEVELOPMENT_TIMESERIES

      # LAYER 3: PEOPLE IMPACT
      - name: IRS_ORIGIN_DESTINATION_MIGRATION_TIMESERIES
      - name: IRS_MIGRATION_BY_CHARACTERISTIC_TIMESERIES
      - name: IRS_MIGRATION_BY_CHARACTERISTIC_ATTRIBUTES
      - name: USPS_ADDRESS_CHANGE_TIMESERIES
      - name: USPS_ADDRESS_CHANGE_ATTRIBUTES
      - name: BUREAU_OF_LABOR_STATISTICS_EMPLOYMENT_TIMESERIES
      - name: BUREAU_OF_LABOR_STATISTICS_EMPLOYMENT_ATTRIBUTES
      - name: US_DEPARTMENT_OF_LABOR_UNEMPLOYMENT_INSURANCE_CLAIMS_TIMESERIES

      # LAYER 4: CONTEXT
      - name: AMERICAN_COMMUNITY_SURVEY_TIMESERIES
      - name: AMERICAN_COMMUNITY_SURVEY_ATTRIBUTES
      - name: IRS_INDIVIDUAL_INCOME_TIMESERIES
      - name: US_ECONOMIC_CENSUS_TIMESERIES

      - name: NOAA_WEATHER_STATION_INDEX
      - name: NOAA_WEATHER_METRICS_ATTRIBUTES
      - name: NOAA_WEATHER_METRICS_TIMESERIES
      - name: NOAA_NWRFC_STATION_INDEX
      - name: NOAA_NWRFC_WATER_SUPPLY_ATTRIBUTES
      - name: NOAA_NWRFC_WATER_SUPPLY_TIMESERIES
      - name: NWS_WEATHER_ALERT_EVENTS
      - name: NWS_WEATHER_ALERT_RELATIONSHIPS
      - name: NWS_WEATHER_ATTRIBUTES
      - name: NWS_WEATHER_TIMESERIES
      - name: NWS_WEATHER_STATION_INDEX
      - name: NWS_WEATHER_FORECAST_EVENTS
      - name: NWS_WEATHER_ZONE_INDEX

      
