{{ config(materialized='table') }}

SELECT
    GEO_ID,
    FORECAST_TYPE,
    FORECAST_NAME,
    FORECAST_NUMBER,
    IS_DAYTIME,
    TEMPERATURE,
    WINDSPEED,
    WIND_DIRECTION,
    PRECIPITATION,
    SHORT_FORECAST,
    DETAILED_FORECAST,
    ELEVATION,
    START_TIMESTAMP,
    END_TIMESTAMP,
    GENERATED_TIMESTAMP,
    UPDATE_TIMESTAMP
FROM {{ source('snowflake_public_data', 'NWS_WEATHER_FORECAST_EVENTS') }}
