SELECT
    NOAA_WEATHER_STATION_ID,
    NOAA_WEATHER_STATION_NAME,
    LATITUDE,
    LONGITUDE,
    ELEVATION,
    COUNTRY_GEO_ID,
    COUNTRY_NAME,
    STATE_GEO_ID,
    STATE_NAME,
    ZIP_GEO_ID,
    ZIP_NAME,
    WEATHER_STATION_NETWORK,
    WORLD_METEOROLOGICAL_ORGANIZATION_ID,
    ASSOCIATED_NETWORKS,
    SOURCE_DATA
FROM {{ source('snowflake_public_data', 'NOAA_WEATHER_STATION_INDEX') }}
