{{ config(materialized='table') }}

SELECT 
    COUNTY_GEO_ID,
    NWS_ALERT_ID,
    ALERT_STATUS,
    ALERT_TYPE,
    NWS_REPORTER,
    ALERT_TITLE,
    ALERT_DESCRIPTION,
    ALERT_INSTRUCTION,
    EVENT_TYPE,
    EVENT_CATEGORY,
    EVENT_CERTAINTY,
    EVENT_SEVERITY,
    EVENT_URGENCY,
    SENT_TIMESTAMP,
    EFFECTIVE_TIMESTAMP,
    EXPIRATION_TIMESTAMP,
    ONSET_TIMESTAMP
FROM {{ source('snowflake_public_data', 'NWS_WEATHER_ALERT_EVENTS') }}
where SENT_TIMESTAMP >= '2024-01-01'