SELECT
    NWS_WEATHER_STATION_ID,
    NWS_WEATHER_STATION_NAME,
    COUNTY_GEO_ID,
    STATE_GEO_ID,
    LATITUDE,
    LONGITUDE,
    ELEVATION,
    TIMEZONE,
    FORECAST_ZONE_ID,
    FIRE_WEATHER_ZONE_ID
FROM {{ source('snowflake_public_data', 'NWS_WEATHER_STATION_INDEX') }}
