SELECT
    DISASTER_DECLARATION_RECORD_ID,
    DISASTER_ID,
    FEMA_DESIGNATED_AREA,
    FEMA_PLACE_CODE,
    FEMA_REGION_ID,
    STATE_GEO_ID,
    COUNTY_GEO_ID,
    DESIGNATED_DATE,
    CLOSEOUT_DATE,
    ENTRY_DATE,
    UPDATE_DATE,
    TRIBAL_REQUEST,
    DECLARED_PROGRAMS_DETAILED
FROM {{ source('snowflake_public_data', 'FEMA_DISASTER_DECLARATION_AREAS_INDEX') }}