SELECT 
    FEMA_DI.DISASTER_ID,
    FEMA_DI.DISASTER_DECLARATION_DATE,
    FEMA_DI.DISASTER_DECLARATION_TYPE,
    FEMA_DI.DISASTER_BEGIN_DATE,
    FEMA_DI.DISASTER_END_DATE,
    FEMA_DI.DISASTER_TYPE,
    GEO.COUNTY_GEOID,
    GEO.CENSUSTRACT_GEOID,
    GEO.CENSUSTRACT_GEONAME,
    GEO.COUNTY_GEONAME,
    GEO.STATE_GEONAME,
    GEO.COUNTRY_GEONAME,
    GEO.CONTINENT_GEONAME
FROM {{ref('int_fema_disasters_index') }} as FEMA_DI 
    left join {{ref('int_geography') }} as GEO on 
        FEMA_DI.COUNTY_GEOID_FEMA = GEO.COUNTY_GEOID
 



